// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoGIXd4m1dTce2b0nwMbFkqfiBXWgPd6M',
    appId: '1:537913184680:web:fb0815e67efeee93230d9d',
    messagingSenderId: '537913184680',
    projectId: 'buildaplushtoystore',
    authDomain: 'buildaplushtoystore.firebaseapp.com',
    storageBucket: 'buildaplushtoystore.firebasestorage.app',
    measurementId: 'G-7JLP7NMXTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTDUkJp4m_CLXaRSDt3wBlErKR5yMAq3g',
    appId: '1:537913184680:android:c4891f3509c36a28230d9d',
    messagingSenderId: '537913184680',
    projectId: 'buildaplushtoystore',
    storageBucket: 'buildaplushtoystore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgyhfRolpo96WH4nswbxWjQo0RvyHzG6c',
    appId: '1:537913184680:ios:58d7adee60975d20230d9d',
    messagingSenderId: '537913184680',
    projectId: 'buildaplushtoystore',
    storageBucket: 'buildaplushtoystore.firebasestorage.app',
    iosBundleId: 'com.example.appdevproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgyhfRolpo96WH4nswbxWjQo0RvyHzG6c',
    appId: '1:537913184680:ios:58d7adee60975d20230d9d',
    messagingSenderId: '537913184680',
    projectId: 'buildaplushtoystore',
    storageBucket: 'buildaplushtoystore.firebasestorage.app',
    iosBundleId: 'com.example.appdevproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoGIXd4m1dTce2b0nwMbFkqfiBXWgPd6M',
    appId: '1:537913184680:web:6a8332cdea88d866230d9d',
    messagingSenderId: '537913184680',
    projectId: 'buildaplushtoystore',
    authDomain: 'buildaplushtoystore.firebaseapp.com',
    storageBucket: 'buildaplushtoystore.firebasestorage.app',
    measurementId: 'G-MK12JN6ZB8',
  );
}
